/******************************************************************************
** Copyright (c) 2013-2018, Alexander Heinecke                               **
** All rights reserved.                                                      **
**                                                                           **
** Redistribution and use in source and binary forms, with or without        **
** modification, are permitted provided that the following conditions        **
** are met:                                                                  **
** 1. Redistributions of source code must retain the above copyright         **
**    notice, this list of conditions and the following disclaimer.          **
** 2. Redistributions in binary form must reproduce the above copyright      **
**    notice, this list of conditions and the following disclaimer in the    **
**    documentation and/or other materials provided with the distribution.   **
** 3. Neither the name of the copyright holder nor the names of its          **
**    contributors may be used to endorse or promote products derived        **
**    from this software without specific prior written permission.          **
**                                                                           **
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS       **
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT         **
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR     **
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT      **
** HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,    **
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED  **
** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR    **
** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF    **
** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING      **
** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS        **
** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.              **
******************************************************************************/

#ifdef BENCH_AVX512_QFMA
void gflops_float_qfma(float* data) {
    __asm__ __volatile__("movq %0, %%r8\n\t"
                         "vmovups (%%r8),  %%zmm0\n\t"
                         "vmovups (%%r8),  %%zmm1\n\t"
                         "vmovups (%%r8),  %%zmm2\n\t"
                         "vmovups (%%r8),  %%zmm3\n\t"
                         "vmovups (%%r8),  %%zmm4\n\t"
                         "vmovups (%%r8),  %%zmm5\n\t"
                         "vmovups (%%r8),  %%zmm6\n\t"
                         "vmovups (%%r8),  %%zmm7\n\t"
                         "vmovups (%%r8),  %%zmm8\n\t"
                         "vmovups (%%r8),  %%zmm9\n\t"
                         "vmovups (%%r8), %%zmm10\n\t"
                         "vmovups (%%r8), %%zmm11\n\t"
                         "vmovups (%%r8), %%zmm12\n\t"
                         "vmovups (%%r8), %%zmm13\n\t"
                         "vmovups (%%r8), %%zmm14\n\t"
                         "vmovups (%%r8), %%zmm15\n\t"
                         "vmovups (%%r8), %%zmm16\n\t"
                         "vmovups (%%r8), %%zmm17\n\t"
                         "vmovups (%%r8), %%zmm18\n\t"
                         "vmovups (%%r8), %%zmm19\n\t"
                         "vmovups (%%r8), %%zmm20\n\t"
                         "vmovups (%%r8), %%zmm21\n\t"
                         "vmovups (%%r8), %%zmm22\n\t"
                         "vmovups (%%r8), %%zmm23\n\t"
                         "vmovups (%%r8), %%zmm24\n\t"
                         "vmovups (%%r8), %%zmm25\n\t"
                         "vmovups (%%r8), %%zmm26\n\t"
                         "vmovups (%%r8), %%zmm27\n\t"
                         "vmovups (%%r8), %%zmm28\n\t"
                         "vmovups (%%r8), %%zmm29\n\t"
                         "vmovups (%%r8), %%zmm30\n\t"
                         "vmovups (%%r8), %%zmm31\n\t"
                         "movq $100000000, %%r9\n\t" 
                         "1:\n\t"
                         "subq $1, %%r9\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm4\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm5\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm6\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm7\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm8\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm9\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm10\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm11\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm12\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm13\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm14\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm15\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm16\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm17\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm18\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm19\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm20\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm21\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm22\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm23\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm24\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm25\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm26\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm27\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm28\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm29\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm30\n\t"
                         "v4fmaddps  (%%r8),  %%zmm0,  %%zmm31\n\t"
                         "cmpq $0, %%r9\n\t"
                         "jg 1b\n\t"
                        : : "m"(data) : "r8","r9","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15","xmm16","xmm17","xmm18","xmm19","xmm20","xmm21","xmm22","xmm23","xmm24","xmm25","xmm26","xmm27","xmm28","xmm29","xmm30","xmm31");
}
#else
void gflops_float_qfma(float* data) {
#ifdef _OPENMP
  #pragma omp single
  {
#endif
  std::cout << "QFMA is not available on this architecture" << std::endl;
#ifdef _OPENMP
  }
#endif
}
#endif

void gflops_float_fma(float* data) {
    __asm__ __volatile__("movq %0, %%r8\n\t"
                         "vmovups (%%r8),  %%zmm0\n\t"
                         "vmovups (%%r8),  %%zmm1\n\t"
                         "vmovups (%%r8),  %%zmm2\n\t"
                         "vmovups (%%r8),  %%zmm3\n\t"
                         "vmovups (%%r8),  %%zmm4\n\t"
                         "vmovups (%%r8),  %%zmm5\n\t"
                         "vmovups (%%r8),  %%zmm6\n\t"
                         "vmovups (%%r8),  %%zmm7\n\t"
                         "vmovups (%%r8),  %%zmm8\n\t"
                         "vmovups (%%r8),  %%zmm9\n\t"
                         "vmovups (%%r8), %%zmm10\n\t"
                         "vmovups (%%r8), %%zmm11\n\t"
                         "vmovups (%%r8), %%zmm12\n\t"
                         "vmovups (%%r8), %%zmm13\n\t"
                         "vmovups (%%r8), %%zmm14\n\t"
                         "vmovups (%%r8), %%zmm15\n\t"
                         "vmovups (%%r8), %%zmm16\n\t"
                         "vmovups (%%r8), %%zmm17\n\t"
                         "vmovups (%%r8), %%zmm18\n\t"
                         "vmovups (%%r8), %%zmm19\n\t"
                         "vmovups (%%r8), %%zmm20\n\t"
                         "vmovups (%%r8), %%zmm21\n\t"
                         "vmovups (%%r8), %%zmm22\n\t"
                         "vmovups (%%r8), %%zmm23\n\t"
                         "vmovups (%%r8), %%zmm24\n\t"
                         "vmovups (%%r8), %%zmm25\n\t"
                         "vmovups (%%r8), %%zmm26\n\t"
                         "vmovups (%%r8), %%zmm27\n\t"
                         "vmovups (%%r8), %%zmm28\n\t"
                         "vmovups (%%r8), %%zmm29\n\t"
                         "vmovups (%%r8), %%zmm30\n\t"
                         "vmovups (%%r8), %%zmm31\n\t"
                         "movq $100000000, %%r9\n\t" 
                         "1:\n\t"
                         "subq $1, %%r9\n\t"
                         "vfmadd231ps  %%zmm0,  %%zmm0,  %%zmm0\n\t"
                         "vfmadd231ps  %%zmm1,  %%zmm1,  %%zmm1\n\t"
                         "vfmadd231ps  %%zmm2,  %%zmm2,  %%zmm2\n\t"
                         "vfmadd231ps  %%zmm3,  %%zmm3,  %%zmm3\n\t"
                         "vfmadd231ps  %%zmm4,  %%zmm4,  %%zmm4\n\t"
                         "vfmadd231ps  %%zmm5,  %%zmm5,  %%zmm5\n\t"
                         "vfmadd231ps  %%zmm6,  %%zmm6,  %%zmm6\n\t"
                         "vfmadd231ps  %%zmm7,  %%zmm7,  %%zmm7\n\t"
                         "vfmadd231ps  %%zmm8,  %%zmm8,  %%zmm8\n\t"
                         "vfmadd231ps  %%zmm9,  %%zmm9,  %%zmm9\n\t"
                         "vfmadd231ps %%zmm10, %%zmm10, %%zmm10\n\t"
                         "vfmadd231ps %%zmm11, %%zmm11, %%zmm11\n\t"
                         "vfmadd231ps %%zmm12, %%zmm12, %%zmm12\n\t"
                         "vfmadd231ps %%zmm13, %%zmm13, %%zmm13\n\t"
                         "vfmadd231ps %%zmm14, %%zmm14, %%zmm14\n\t"
                         "vfmadd231ps %%zmm15, %%zmm15, %%zmm15\n\t"
                         "vfmadd231ps %%zmm16, %%zmm16, %%zmm16\n\t"
                         "vfmadd231ps %%zmm17, %%zmm17, %%zmm17\n\t"
                         "vfmadd231ps %%zmm18, %%zmm18, %%zmm18\n\t"
                         "vfmadd231ps %%zmm19, %%zmm19, %%zmm19\n\t"
                         "vfmadd231ps %%zmm20, %%zmm20, %%zmm20\n\t"
                         "vfmadd231ps %%zmm21, %%zmm21, %%zmm21\n\t"
                         "vfmadd231ps %%zmm22, %%zmm22, %%zmm22\n\t"
                         "vfmadd231ps %%zmm23, %%zmm23, %%zmm23\n\t"
                         "vfmadd231ps %%zmm24, %%zmm24, %%zmm24\n\t"
                         "vfmadd231ps %%zmm25, %%zmm25, %%zmm25\n\t"
                         "vfmadd231ps %%zmm26, %%zmm26, %%zmm26\n\t"
                         "vfmadd231ps %%zmm27, %%zmm27, %%zmm27\n\t"
                         "vfmadd231ps %%zmm28, %%zmm28, %%zmm28\n\t"
                         "vfmadd231ps %%zmm29, %%zmm29, %%zmm29\n\t"
                         "vfmadd231ps %%zmm30, %%zmm30, %%zmm30\n\t"
                         "vfmadd231ps %%zmm31, %%zmm31, %%zmm31\n\t"
                         "cmpq $0, %%r9\n\t"
                         "jg 1b\n\t"
                        : : "m"(data) : "r8","r9","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15","xmm16","xmm17","xmm18","xmm19","xmm20","xmm21","xmm22","xmm23","xmm24","xmm25","xmm26","xmm27","xmm28","xmm29","xmm30","xmm31");
}

void gflops_float_mul(float* data) {
    __asm__ __volatile__("movq %0, %%r8\n\t"
                         "vmovups (%%r8),  %%zmm0\n\t"
                         "vmovups (%%r8),  %%zmm1\n\t"
                         "vmovups (%%r8),  %%zmm2\n\t"
                         "vmovups (%%r8),  %%zmm3\n\t"
                         "vmovups (%%r8),  %%zmm4\n\t"
                         "vmovups (%%r8),  %%zmm5\n\t"
                         "vmovups (%%r8),  %%zmm6\n\t"
                         "vmovups (%%r8),  %%zmm7\n\t"
                         "vmovups (%%r8),  %%zmm8\n\t"
                         "vmovups (%%r8),  %%zmm9\n\t"
                         "vmovups (%%r8), %%zmm10\n\t"
                         "vmovups (%%r8), %%zmm11\n\t"
                         "vmovups (%%r8), %%zmm12\n\t"
                         "vmovups (%%r8), %%zmm13\n\t"
                         "vmovups (%%r8), %%zmm14\n\t"
                         "vmovups (%%r8), %%zmm15\n\t"
                         "vmovups (%%r8), %%zmm16\n\t"
                         "vmovups (%%r8), %%zmm17\n\t"
                         "vmovups (%%r8), %%zmm18\n\t"
                         "vmovups (%%r8), %%zmm19\n\t"
                         "vmovups (%%r8), %%zmm20\n\t"
                         "vmovups (%%r8), %%zmm21\n\t"
                         "vmovups (%%r8), %%zmm22\n\t"
                         "vmovups (%%r8), %%zmm23\n\t"
                         "vmovups (%%r8), %%zmm24\n\t"
                         "vmovups (%%r8), %%zmm25\n\t"
                         "vmovups (%%r8), %%zmm26\n\t"
                         "vmovups (%%r8), %%zmm27\n\t"
                         "vmovups (%%r8), %%zmm28\n\t"
                         "vmovups (%%r8), %%zmm29\n\t"
                         "vmovups (%%r8), %%zmm30\n\t"
                         "vmovups (%%r8), %%zmm31\n\t"
                         "movq $100000000, %%r9\n\t" 
                         "1:\n\t"
                         "subq $1, %%r9\n\t"
                         "vmulps  %%zmm0,  %%zmm0,  %%zmm0\n\t"
                         "vmulps  %%zmm1,  %%zmm1,  %%zmm1\n\t"
                         "vmulps  %%zmm2,  %%zmm2,  %%zmm2\n\t"
                         "vmulps  %%zmm3,  %%zmm3,  %%zmm3\n\t"
                         "vmulps  %%zmm4,  %%zmm4,  %%zmm4\n\t"
                         "vmulps  %%zmm5,  %%zmm5,  %%zmm5\n\t"
                         "vmulps  %%zmm6,  %%zmm6,  %%zmm6\n\t"
                         "vmulps  %%zmm7,  %%zmm7,  %%zmm7\n\t"
                         "vmulps  %%zmm8,  %%zmm8,  %%zmm8\n\t"
                         "vmulps  %%zmm9,  %%zmm9,  %%zmm9\n\t"
                         "vmulps %%zmm10, %%zmm10, %%zmm10\n\t"
                         "vmulps %%zmm11, %%zmm11, %%zmm11\n\t"
                         "vmulps %%zmm12, %%zmm12, %%zmm12\n\t"
                         "vmulps %%zmm13, %%zmm13, %%zmm13\n\t"
                         "vmulps %%zmm14, %%zmm14, %%zmm14\n\t"
                         "vmulps %%zmm15, %%zmm15, %%zmm15\n\t"
                         "vmulps %%zmm16, %%zmm16, %%zmm16\n\t"
                         "vmulps %%zmm17, %%zmm17, %%zmm17\n\t"
                         "vmulps %%zmm18, %%zmm18, %%zmm18\n\t"
                         "vmulps %%zmm19, %%zmm19, %%zmm19\n\t"
                         "vmulps %%zmm20, %%zmm20, %%zmm20\n\t"
                         "vmulps %%zmm21, %%zmm21, %%zmm21\n\t"
                         "vmulps %%zmm22, %%zmm22, %%zmm22\n\t"
                         "vmulps %%zmm23, %%zmm23, %%zmm23\n\t"
                         "vmulps %%zmm24, %%zmm24, %%zmm24\n\t"
                         "vmulps %%zmm25, %%zmm25, %%zmm25\n\t"
                         "vmulps %%zmm26, %%zmm26, %%zmm26\n\t"
                         "vmulps %%zmm27, %%zmm27, %%zmm27\n\t"
                         "vmulps %%zmm28, %%zmm28, %%zmm28\n\t"
                         "vmulps %%zmm29, %%zmm29, %%zmm29\n\t"
                         "vmulps %%zmm30, %%zmm30, %%zmm30\n\t"
                         "vmulps %%zmm31, %%zmm31, %%zmm31\n\t"
                         "cmpq $0, %%r9\n\t"
                         "jg 1b\n\t"
                         : : "m"(data) : "r8","r9","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15","xmm16","xmm17","xmm18","xmm19","xmm20","xmm21","xmm22","xmm23","xmm24","xmm25","xmm26","xmm27","xmm28","xmm29","xmm30","xmm31");
}

void gflops_float_add(float* data) {
    __asm__ __volatile__("movq %0, %%r8\n\t"
                         "vmovups (%%r8),  %%zmm0\n\t"
                         "vmovups (%%r8),  %%zmm1\n\t"
                         "vmovups (%%r8),  %%zmm2\n\t"
                         "vmovups (%%r8),  %%zmm3\n\t"
                         "vmovups (%%r8),  %%zmm4\n\t"
                         "vmovups (%%r8),  %%zmm5\n\t"
                         "vmovups (%%r8),  %%zmm6\n\t"
                         "vmovups (%%r8),  %%zmm7\n\t"
                         "vmovups (%%r8),  %%zmm8\n\t"
                         "vmovups (%%r8),  %%zmm9\n\t"
                         "vmovups (%%r8), %%zmm10\n\t"
                         "vmovups (%%r8), %%zmm11\n\t"
                         "vmovups (%%r8), %%zmm12\n\t"
                         "vmovups (%%r8), %%zmm13\n\t"
                         "vmovups (%%r8), %%zmm14\n\t"
                         "vmovups (%%r8), %%zmm15\n\t"
                         "vmovups (%%r8), %%zmm16\n\t"
                         "vmovups (%%r8), %%zmm17\n\t"
                         "vmovups (%%r8), %%zmm18\n\t"
                         "vmovups (%%r8), %%zmm19\n\t"
                         "vmovups (%%r8), %%zmm20\n\t"
                         "vmovups (%%r8), %%zmm21\n\t"
                         "vmovups (%%r8), %%zmm22\n\t"
                         "vmovups (%%r8), %%zmm23\n\t"
                         "vmovups (%%r8), %%zmm24\n\t"
                         "vmovups (%%r8), %%zmm25\n\t"
                         "vmovups (%%r8), %%zmm26\n\t"
                         "vmovups (%%r8), %%zmm27\n\t"
                         "vmovups (%%r8), %%zmm28\n\t"
                         "vmovups (%%r8), %%zmm29\n\t"
                         "vmovups (%%r8), %%zmm30\n\t"
                         "vmovups (%%r8), %%zmm31\n\t"
                         "movq $100000000, %%r9\n\t" 
                         "1:\n\t"
                         "subq $1, %%r9\n\t"
                         "vaddps  %%zmm0,  %%zmm0,  %%zmm0\n\t"
                         "vaddps  %%zmm1,  %%zmm1,  %%zmm1\n\t"
                         "vaddps  %%zmm2,  %%zmm2,  %%zmm2\n\t"
                         "vaddps  %%zmm3,  %%zmm3,  %%zmm3\n\t"
                         "vaddps  %%zmm4,  %%zmm4,  %%zmm4\n\t"
                         "vaddps  %%zmm5,  %%zmm5,  %%zmm5\n\t"
                         "vaddps  %%zmm6,  %%zmm6,  %%zmm6\n\t"
                         "vaddps  %%zmm7,  %%zmm7,  %%zmm7\n\t"
                         "vaddps  %%zmm8,  %%zmm8,  %%zmm8\n\t"
                         "vaddps  %%zmm9,  %%zmm9,  %%zmm9\n\t"
                         "vaddps %%zmm10, %%zmm10, %%zmm10\n\t"
                         "vaddps %%zmm11, %%zmm11, %%zmm11\n\t"
                         "vaddps %%zmm12, %%zmm12, %%zmm12\n\t"
                         "vaddps %%zmm13, %%zmm13, %%zmm13\n\t"
                         "vaddps %%zmm14, %%zmm14, %%zmm14\n\t"
                         "vaddps %%zmm15, %%zmm15, %%zmm15\n\t"
                         "vaddps %%zmm16, %%zmm16, %%zmm16\n\t"
                         "vaddps %%zmm17, %%zmm17, %%zmm17\n\t"
                         "vaddps %%zmm18, %%zmm18, %%zmm18\n\t"
                         "vaddps %%zmm19, %%zmm19, %%zmm19\n\t"
                         "vaddps %%zmm20, %%zmm20, %%zmm20\n\t"
                         "vaddps %%zmm21, %%zmm21, %%zmm21\n\t"
                         "vaddps %%zmm22, %%zmm22, %%zmm22\n\t"
                         "vaddps %%zmm23, %%zmm23, %%zmm23\n\t"
                         "vaddps %%zmm24, %%zmm24, %%zmm24\n\t"
                         "vaddps %%zmm25, %%zmm25, %%zmm25\n\t"
                         "vaddps %%zmm26, %%zmm26, %%zmm26\n\t"
                         "vaddps %%zmm27, %%zmm27, %%zmm27\n\t"
                         "vaddps %%zmm28, %%zmm28, %%zmm28\n\t"
                         "vaddps %%zmm29, %%zmm29, %%zmm29\n\t"
                         "vaddps %%zmm30, %%zmm30, %%zmm30\n\t"
                         "vaddps %%zmm31, %%zmm31, %%zmm31\n\t"
                         "cmpq $0, %%r9\n\t"
                         "jg 1b\n\t"
                         : : "m"(data) : "r8","r9","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15","xmm16","xmm17","xmm18","xmm19","xmm20","xmm21","xmm22","xmm23","xmm24","xmm25","xmm26","xmm27","xmm28","xmm29","xmm30","xmm31");
}

void gflops_float_madd(float* data) {
    __asm__ __volatile__("movq %0, %%r8\n\t"
                         "vmovups (%%r8),  %%zmm0\n\t"
                         "vmovups (%%r8),  %%zmm1\n\t"
                         "vmovups (%%r8),  %%zmm2\n\t"
                         "vmovups (%%r8),  %%zmm3\n\t"
                         "vmovups (%%r8),  %%zmm4\n\t"
                         "vmovups (%%r8),  %%zmm5\n\t"
                         "vmovups (%%r8),  %%zmm6\n\t"
                         "vmovups (%%r8),  %%zmm7\n\t"
                         "vmovups (%%r8),  %%zmm8\n\t"
                         "vmovups (%%r8),  %%zmm9\n\t"
                         "vmovups (%%r8), %%zmm10\n\t"
                         "vmovups (%%r8), %%zmm11\n\t"
                         "vmovups (%%r8), %%zmm12\n\t"
                         "vmovups (%%r8), %%zmm13\n\t"
                         "vmovups (%%r8), %%zmm14\n\t"
                         "vmovups (%%r8), %%zmm15\n\t"
                         "vmovups (%%r8), %%zmm16\n\t"
                         "vmovups (%%r8), %%zmm17\n\t"
                         "vmovups (%%r8), %%zmm18\n\t"
                         "vmovups (%%r8), %%zmm19\n\t"
                         "vmovups (%%r8), %%zmm20\n\t"
                         "vmovups (%%r8), %%zmm21\n\t"
                         "vmovups (%%r8), %%zmm22\n\t"
                         "vmovups (%%r8), %%zmm23\n\t"
                         "vmovups (%%r8), %%zmm24\n\t"
                         "vmovups (%%r8), %%zmm25\n\t"
                         "vmovups (%%r8), %%zmm26\n\t"
                         "vmovups (%%r8), %%zmm27\n\t"
                         "vmovups (%%r8), %%zmm28\n\t"
                         "vmovups (%%r8), %%zmm29\n\t"
                         "vmovups (%%r8), %%zmm30\n\t"
                         "vmovups (%%r8), %%zmm31\n\t"
                         "movq $100000000, %%r9\n\t" 
                         "1:\n\t"
                         "subq $1, %%r9\n\t"
                         "vmulps  %%zmm0,  %%zmm0,  %%zmm0\n\t"
                         "vaddps  %%zmm1,  %%zmm1,  %%zmm1\n\t"
                         "vmulps  %%zmm2,  %%zmm2,  %%zmm2\n\t"
                         "vaddps  %%zmm3,  %%zmm3,  %%zmm3\n\t"
                         "vmulps  %%zmm4,  %%zmm4,  %%zmm4\n\t"
                         "vaddps  %%zmm5,  %%zmm5,  %%zmm5\n\t"
                         "vmulps  %%zmm6,  %%zmm6,  %%zmm6\n\t"
                         "vaddps  %%zmm7,  %%zmm7,  %%zmm7\n\t"
                         "vmulps  %%zmm8,  %%zmm8,  %%zmm8\n\t"
                         "vaddps  %%zmm9,  %%zmm9,  %%zmm9\n\t"
                         "vmulps %%zmm10, %%zmm10, %%zmm10\n\t"
                         "vaddps %%zmm11, %%zmm11, %%zmm11\n\t"
                         "vmulps %%zmm12, %%zmm12, %%zmm12\n\t"
                         "vaddps %%zmm13, %%zmm13, %%zmm13\n\t"
                         "vmulps %%zmm14, %%zmm14, %%zmm14\n\t"
                         "vaddps %%zmm15, %%zmm15, %%zmm15\n\t"
                         "vmulps %%zmm16, %%zmm16, %%zmm16\n\t"
                         "vaddps %%zmm17, %%zmm17, %%zmm17\n\t"
                         "vmulps %%zmm18, %%zmm18, %%zmm18\n\t"
                         "vaddps %%zmm19, %%zmm19, %%zmm19\n\t"
                         "vmulps %%zmm20, %%zmm20, %%zmm20\n\t"
                         "vaddps %%zmm21, %%zmm21, %%zmm21\n\t"
                         "vmulps %%zmm22, %%zmm22, %%zmm22\n\t"
                         "vaddps %%zmm23, %%zmm23, %%zmm23\n\t"
                         "vmulps %%zmm24, %%zmm24, %%zmm24\n\t"
                         "vaddps %%zmm25, %%zmm25, %%zmm25\n\t"
                         "vmulps %%zmm26, %%zmm26, %%zmm26\n\t"
                         "vaddps %%zmm27, %%zmm27, %%zmm27\n\t"
                         "vmulps %%zmm28, %%zmm28, %%zmm28\n\t"
                         "vaddps %%zmm29, %%zmm29, %%zmm29\n\t"
                         "vmulps %%zmm30, %%zmm30, %%zmm30\n\t"
                         "vaddps %%zmm31, %%zmm31, %%zmm31\n\t"
                         "cmpq $0, %%r9\n\t"
                         "jg 1b\n\t"
                         : : "m"(data) : "r8","r9","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15","xmm16","xmm17","xmm18","xmm19","xmm20","xmm21","xmm22","xmm23","xmm24","xmm25","xmm26","xmm27","xmm28","xmm29","xmm30","xmm31");
}

